export const MakesArray = [
  { id: 344, make_id: 39, name: "1500", make: { id: 39, name: "Ram" } },
  { id: 140, make_id: 3, name: "2 Series", make: { id: 3, name: "BMW" } },
  { id: 532, make_id: 26, name: "200", make: { id: 26, name: "Chrysler" } },
  { id: 345, make_id: 39, name: "2500", make: { id: 39, name: "Ram" } },
  { id: 286, make_id: 16, name: "3", make: { id: 16, name: "Mazda" } },
  { id: 9, make_id: 3, name: "3 Series", make: { id: 3, name: "BMW" } },
  {
    id: 462,
    make_id: 3,
    name: "3 Series Gran Turismo",
    make: { id: 3, name: "BMW" },
  },
  { id: 170, make_id: 26, name: "300", make: { id: 26, name: "Chrysler" } },
  { id: 346, make_id: 39, name: "3500", make: { id: 39, name: "Ram" } },
  { id: 454, make_id: 19, name: "370Z", make: { id: 19, name: "Nissan" } },
  { id: 10, make_id: 3, name: "4 Series", make: { id: 3, name: "BMW" } },
  {
    id: 11,
    make_id: 3,
    name: "4 Series Gran Coupe",
    make: { id: 3, name: "BMW" },
  },
  {
    id: 595,
    make_id: 46,
    name: "458 Italia",
    make: { id: 46, name: "Ferrari" },
  },
  { id: 422, make_id: 24, name: "4C", make: { id: 24, name: "Alfa Romeo" } },
  { id: 360, make_id: 22, name: "4Runner", make: { id: 22, name: "Toyota" } },
  { id: 603, make_id: 16, name: "5", make: { id: 16, name: "Mazda" } },
  { id: 142, make_id: 3, name: "5 Series", make: { id: 3, name: "BMW" } },
  {
    id: 528,
    make_id: 3,
    name: "5 Series Gran Turismo",
    make: { id: 3, name: "BMW" },
  },
  { id: 480, make_id: 28, name: "500", make: { id: 28, name: "FIAT" } },
  { id: 481, make_id: 28, name: "500e", make: { id: 28, name: "FIAT" } },
  { id: 434, make_id: 28, name: "500L", make: { id: 28, name: "FIAT" } },
  { id: 407, make_id: 16, name: "6", make: { id: 16, name: "Mazda" } },
  { id: 508, make_id: 3, name: "6 Series", make: { id: 3, name: "BMW" } },
  {
    id: 463,
    make_id: 3,
    name: "6 Series Gran Coupe",
    make: { id: 3, name: "BMW" },
  },
  {
    id: 604,
    make_id: 36,
    name: "650S Coupe",
    make: { id: 36, name: "McLaren" },
  },
  {
    id: 605,
    make_id: 36,
    name: "650S Spider",
    make: { id: 36, name: "McLaren" },
  },
  { id: 143, make_id: 3, name: "7 Series", make: { id: 3, name: "BMW" } },
  { id: 338, make_id: 38, name: "911", make: { id: 38, name: "Porsche" } },
  {
    id: 614,
    make_id: 38,
    name: "918 Spyder",
    make: { id: 38, name: "Porsche" },
  },
  { id: 103, make_id: 2, name: "A3", make: { id: 2, name: "Audi" } },
  { id: 104, make_id: 2, name: "A4", make: { id: 2, name: "Audi" } },
  { id: 3, make_id: 2, name: "A5", make: { id: 2, name: "Audi" } },
  { id: 106, make_id: 2, name: "A6", make: { id: 2, name: "Audi" } },
  { id: 108, make_id: 2, name: "A7", make: { id: 2, name: "Audi" } },
  { id: 109, make_id: 2, name: "A8", make: { id: 2, name: "Audi" } },
  { id: 39, make_id: 8, name: "Acadia", make: { id: 8, name: "GMC" } },
  { id: 223, make_id: 10, name: "Accent", make: { id: 10, name: "Hyundai" } },
  { id: 214, make_id: 9, name: "Accord", make: { id: 9, name: "Honda" } },
  {
    id: 215,
    make_id: 9,
    name: "Accord Hybrid",
    make: { id: 9, name: "Honda" },
  },
  { id: 554, make_id: 3, name: "ActiveHybrid 5", make: { id: 3, name: "BMW" } },
  { id: 592, make_id: 3, name: "ActiveHybrid 7", make: { id: 3, name: "BMW" } },
  { id: 552, make_id: 2, name: "allroad", make: { id: 2, name: "Audi" } },
  {
    id: 465,
    make_id: 3,
    name: "ALPINA B6 Gran Coupe",
    make: { id: 3, name: "BMW" },
  },
  { id: 144, make_id: 3, name: "ALPINA B7", make: { id: 3, name: "BMW" } },
  { id: 323, make_id: 19, name: "Altima", make: { id: 19, name: "Nissan" } },
  { id: 324, make_id: 19, name: "Armada", make: { id: 19, name: "Nissan" } },
  { id: 509, make_id: 5, name: "ATS", make: { id: 5, name: "Cadillac" } },
  { id: 468, make_id: 5, name: "ATS Coupe", make: { id: 5, name: "Cadillac" } },
  { id: 361, make_id: 22, name: "Avalon", make: { id: 22, name: "Toyota" } },
  {
    id: 362,
    make_id: 22,
    name: "Avalon Hybrid",
    make: { id: 22, name: "Toyota" },
  },
  {
    id: 405,
    make_id: 32,
    name: "Aventador",
    make: { id: 32, name: "Lamborghini" },
  },
  { id: 537, make_id: 10, name: "Azera", make: { id: 10, name: "Hyundai" } },
  {
    id: 542,
    make_id: 37,
    name: "B-Class Electric Drive",
    make: { id: 37, name: "Mercedes-Benz" },
  },
  {
    id: 501,
    make_id: 43,
    name: "Beetle",
    make: { id: 43, name: "Volkswagen" },
  },
  {
    id: 502,
    make_id: 43,
    name: "Beetle Convertible",
    make: { id: 43, name: "Volkswagen" },
  },
  { id: 580, make_id: 38, name: "Boxster", make: { id: 38, name: "Porsche" } },
  { id: 77, make_id: 21, name: "BRZ", make: { id: 21, name: "Subaru" } },
  {
    id: 300,
    make_id: 37,
    name: "C-Class",
    make: { id: 37, name: "Mercedes-Benz" },
  },
  {
    id: 535,
    make_id: 29,
    name: "C-Max Energi",
    make: { id: 29, name: "Ford" },
  },
  {
    id: 512,
    make_id: 29,
    name: "C-Max Hybrid",
    make: { id: 29, name: "Ford" },
  },
  { id: 615, make_id: 39, name: "C/V", make: { id: 39, name: "Ram" } },
  { id: 442, make_id: 13, name: "Cadenza", make: { id: 13, name: "Kia" } },
  {
    id: 563,
    make_id: 46,
    name: "California T",
    make: { id: 46, name: "Ferrari" },
  },
  { id: 158, make_id: 6, name: "Camaro", make: { id: 6, name: "Chevrolet" } },
  { id: 84, make_id: 22, name: "Camry", make: { id: 22, name: "Toyota" } },
  {
    id: 85,
    make_id: 22,
    name: "Camry Hybrid",
    make: { id: 22, name: "Toyota" },
  },
  { id: 203, make_id: 8, name: "Canyon", make: { id: 8, name: "GMC" } },
  {
    id: 594,
    make_id: 6,
    name: "Captiva Sport",
    make: { id: 6, name: "Chevrolet" },
  },
  { id: 339, make_id: 38, name: "Cayenne", make: { id: 38, name: "Porsche" } },
  { id: 581, make_id: 38, name: "Cayman", make: { id: 38, name: "Porsche" } },
  { id: 548, make_id: 43, name: "CC", make: { id: 43, name: "Volkswagen" } },
  { id: 173, make_id: 27, name: "Challenger", make: { id: 27, name: "Dodge" } },
  { id: 174, make_id: 27, name: "Charger", make: { id: 27, name: "Dodge" } },
  { id: 243, make_id: 30, name: "Cherokee", make: { id: 30, name: "Jeep" } },
  {
    id: 510,
    make_id: 6,
    name: "City Express",
    make: { id: 6, name: "Chevrolet" },
  },
  { id: 216, make_id: 9, name: "Civic", make: { id: 9, name: "Honda" } },
  {
    id: 301,
    make_id: 37,
    name: "CLA-Class",
    make: { id: 37, name: "Mercedes-Benz" },
  },
  {
    id: 302,
    make_id: 37,
    name: "CLS-Class",
    make: { id: 37, name: "Mercedes-Benz" },
  },
  { id: 159, make_id: 6, name: "Colorado", make: { id: 6, name: "Chevrolet" } },
  { id: 244, make_id: 30, name: "Compass", make: { id: 30, name: "Jeep" } },
  {
    id: 553,
    make_id: 25,
    name: "Continental GT",
    make: { id: 25, name: "Bentley" },
  },
  {
    id: 591,
    make_id: 25,
    name: "Continental GT3-R",
    make: { id: 25, name: "Bentley" },
  },
  { id: 575, make_id: 17, name: "Cooper", make: { id: 17, name: "MINI" } },
  {
    id: 577,
    make_id: 17,
    name: "Cooper Countryman",
    make: { id: 17, name: "MINI" },
  },
  {
    id: 609,
    make_id: 17,
    name: "Cooper Coupe",
    make: { id: 17, name: "MINI" },
  },
  {
    id: 578,
    make_id: 17,
    name: "Cooper Paceman",
    make: { id: 17, name: "MINI" },
  },
  {
    id: 610,
    make_id: 17,
    name: "Cooper Roadster",
    make: { id: 17, name: "MINI" },
  },
  { id: 364, make_id: 22, name: "Corolla", make: { id: 22, name: "Toyota" } },
  { id: 30, make_id: 6, name: "Corvette", make: { id: 6, name: "Chevrolet" } },
  { id: 217, make_id: 9, name: "CR-V", make: { id: 9, name: "Honda" } },
  { id: 565, make_id: 9, name: "CR-Z", make: { id: 9, name: "Honda" } },
  { id: 597, make_id: 9, name: "Crosstour", make: { id: 9, name: "Honda" } },
  { id: 473, make_id: 6, name: "Cruze", make: { id: 6, name: "Chevrolet" } },
  { id: 540, make_id: 33, name: "CT", make: { id: 33, name: "Lexus" } },
  { id: 470, make_id: 5, name: "CTS", make: { id: 5, name: "Cadillac" } },
  {
    id: 593,
    make_id: 5,
    name: "CTS-V Coupe",
    make: { id: 5, name: "Cadillac" },
  },
  { id: 288, make_id: 16, name: "CX-5", make: { id: 16, name: "Mazda" } },
  { id: 289, make_id: 16, name: "CX-9", make: { id: 16, name: "Mazda" } },
  { id: 562, make_id: 27, name: "Dart", make: { id: 27, name: "Dodge" } },
  { id: 590, make_id: 44, name: "DB9", make: { id: 44, name: "Aston Martin" } },
];

export default {
  MakesArray,
};
